import { test } from "node:test";
import assert from "node:assert/strict";
import { z } from "zod";
import { registeredTools } from "../dist/server.js";
import { classifyRequest } from "../dist/policy.js";
import { quirksFor } from "../dist/reai/quirks.js";

/**
 * Archiving, unarchiving, and the deletion order that decides whether a record can ever go.
 *
 * All of this came out of finding eight orders stranded on the test tenant: generated by a
 * subscription-billing probe, and permanently undeletable because the PRODUCT their lines name was
 * deleted first. Every DELETE on them answers 500 "Referenced record is not accessible", and there
 * is no product unarchive endpoint to restore the reference with.
 */

const tool = (name) => {
  const found = registeredTools.find((t) => t.name === name);
  assert.ok(found, `${name} is not registered`);
  return found;
};

async function run(name, args, data, { status = 200 } = {}) {
  const calls = [];
  const validated = z.object(tool(name).inputSchema).parse({ tenantId: 2783, ...args });
  const result = await tool(name).handler(validated, {
    client: {
      request: async (req) => {
        calls.push(req);
        return { data: typeof data === "function" ? data(req) : data, status };
      },
      deepLink: () => "link",
    },
    config: { writeMode: "full", tenantId: 2783, allowExternalSend: false },
    session: {},
  });
  return { calls, result, text: result.content.find((c) => c.type === "text").text };
}

test("both unarchive tools are registered, reversible, and on the right endpoint", () => {
  for (const [name, path] of [
    ["reai_unarchive_customer", "/api/customers/{id}/unarchive"],
    ["reai_unarchive_supplier", "/api/suppliers/{id}/unarchive"],
  ]) {
    assert.equal(tool(name).risk, "reversible");
    assert.deepEqual(tool(name).apiPaths, [["POST", path]]);
    // Restoring a record is not a write the default mode should refuse.
    assert.equal(classifyRequest("POST", path.replace("{id}", "1")), "reversible");
  }
});

test("unarchiving reports success only when the record actually came back", async () => {
  const ok = await run("reai_unarchive_customer", { id: 5941 }, { id: 5941, name: "Zz Probe", archived: false });
  assert.deepEqual(ok.calls.map((c) => `${c.method} ${c.path}`), ["POST /api/customers/5941/unarchive"]);
  assert.match(ok.text, /active again/);

  // A 200 that leaves archived: true is the case worth catching — nothing was recovered.
  const stuck = await run("reai_unarchive_customer", { id: 5941 }, { id: 5941, archived: true });
  assert.match(stuck.text, /still reads archived: true/);
  assert.match(stuck.text, /Nothing was recovered/);
});

test("the same holds for suppliers", async () => {
  const ok = await run("reai_unarchive_supplier", { id: 5740 }, { id: 5740, name: "Zz Sup", archived: false });
  assert.match(ok.text, /active again/);
  const stuck = await run("reai_unarchive_supplier", { id: 5740 }, { archived: true });
  assert.match(stuck.text, /still reads archived: true/);
});

// The delete endpoints are "delete OR archive" and say which. Reporting "deleted or archived" left
// the caller to guess between a recoverable state and an unrecoverable one.
for (const [name, noun, listTool] of [
  ["reai_delete_customer", "Customer", "reai_list_customers"],
  ["reai_delete_supplier", "Supplier", "reai_list_suppliers"],
]) {
  test(`${name} reads the outcome instead of reporting both`, async () => {
    const deleted = await run(name, { id: 7 }, { outcome: "deleted" });
    assert.match(deleted.text, new RegExp(`${noun} 7 was DELETED outright`));
    assert.match(deleted.text, /nothing to unarchive/);

    const archived = await run(name, { id: 7 }, { outcome: "archived" });
    assert.match(archived.text, new RegExp(`${noun} 7 was ARCHIVED, not deleted`));
    assert.match(archived.text, /archived: true/, "it must say how to see the record again");
    assert.match(archived.text, new RegExp(listTool));
    assert.ok(!/DELETED outright/.test(archived.text));

    for (const data of [null, {}, { outcome: "something" }]) {
      const { text } = await run(name, { id: 7 }, data);
      assert.match(text, /no recognised outcome/, JSON.stringify(data));
    }
  });
}

test("the customer delete names the ordering trap, since archiving is what causes it", () => {
  const description = tool("reai_delete_customer").description;
  assert.match(description, /Referenced record is not accessible/);
  assert.match(description, /Delete the dependents first/);
  assert.match(description, /reai_unarchive_customer/);
});

test("the unarchive tool does not overclaim what it can rescue", () => {
  // Unarchiving the customer was the obvious hypothesis for the stranded orders, and it was tried
  // and failed. A tool that implied otherwise would send the next reader down the same path.
  const description = tool("reai_unarchive_customer").description;
  assert.match(description, /does not make that order deletable again/);
  assert.match(description, /products have no unarchive endpoint/);
});

test("the deletion-order and archive-visibility quirks reach the endpoints they concern", () => {
  const ids = (m, p) => quirksFor(m, p).map((q) => q.id);
  for (const path of ["/api/orders/{id}", "/api/customers/{id}", "/api/products/{id}", "/api/suppliers/{id}"]) {
    assert.ok(
      ids("DELETE", path).includes("delete-a-parent-and-its-children-become-undeletable"),
      `DELETE ${path}`,
    );
  }
  for (const path of ["/api/customers", "/api/suppliers"]) {
    assert.ok(ids("GET", path).includes("archived-records-need-an-explicit-filter-to-see"), path);
  }
  // A read cannot strand anything, so the ordering quirk must not appear on one.
  assert.ok(!ids("GET", "/api/orders").includes("delete-a-parent-and-its-children-become-undeletable"));
});

test("the ordering quirk states the recovery honestly, including what does not work", () => {
  const quirk = quirksFor("DELETE", "/api/orders/{id}").find(
    (q) => q.id === "delete-a-parent-and-its-children-become-undeletable",
  );
  assert.match(quirk.note, /NOT recoverable/);
  assert.match(quirk.note, /remove dependents BEFORE/);
  // Both halves: the endpoints that exist, and the case where they do not help.
  assert.match(quirk.note, /unarchive/);
  assert.match(quirk.note, /the 500\s+persisted/);
  // And the knock-on: an undeletable order takes its subscription with it.
  assert.match(quirk.note, /faktureringshistorikk/);
});

test("the archive-visibility quirk names the filter that works and the one that does not", () => {
  const quirk = quirksFor("GET", "/api/customers").find(
    (q) => q.id === "archived-records-need-an-explicit-filter-to-see",
  );
  assert.match(quirk.note, /`archived=true`/);
  assert.match(quirk.note, /includeArchived=true` is NOT it/);
  // The list tools already expose it, which is what makes the quirk actionable.
  for (const name of ["reai_list_customers", "reai_list_suppliers"]) {
    assert.ok(tool(name).inputSchema.archived, `${name} should take an archived filter`);
  }
});
