import { test } from "node:test";
import assert from "node:assert/strict";
import { z } from "zod";
import { registeredTools } from "../dist/server.js";
import { classifyRequest } from "../dist/policy.js";
import { quirksFor } from "../dist/reai/quirks.js";

/**
 * Archiving, unarchiving, and the deletion order that decides whether a record can ever go.
 *
 * All of this came out of finding eight orders stranded on the test tenant: generated by a
 * subscription-billing probe, and permanently undeletable because the PRODUCT their lines name was
 * deleted first. Every DELETE on them answers 500 "Referenced record is not accessible", and there
 * is no product unarchive endpoint to restore the reference with.
 */

const tool = (name) => {
  const found = registeredTools.find((t) => t.name === name);
  assert.ok(found, `${name} is not registered`);
  return found;
};

async function run(name, args, data, { status = 200 } = {}) {
  const calls = [];
  const validated = z.object(tool(name).inputSchema).parse({ tenantId: 2783, ...args });
  const result = await tool(name).handler(validated, {
    client: {
      request: async (req) => {
        calls.push(req);
        return { data: typeof data === "function" ? data(req) : data, status };
      },
      deepLink: () => "link",
    },
    config: { writeMode: "full", tenantId: 2783, allowExternalSend: false },
    session: {},
  });
  return { calls, result, text: result.content.find((c) => c.type === "text").text };
}

test("both unarchive tools are registered, reversible, and on the right endpoint", () => {
  for (const [name, path] of [
    ["reai_unarchive_customer", "/api/customers/{id}/unarchive"],
    ["reai_unarchive_supplier", "/api/suppliers/{id}/unarchive"],
  ]) {
    assert.equal(tool(name).risk, "reversible");
    assert.deepEqual(tool(name).apiPaths, [["POST", path]]);
    // Restoring a record is not a write the default mode should refuse.
    assert.equal(classifyRequest("POST", path.replace("{id}", "1")), "reversible");
  }
});

for (const [name, noun, listTool] of [
  ["reai_unarchive_customer", "Customer", "reai_list_customers"],
  ["reai_unarchive_supplier", "Supplier", "reai_list_suppliers"],
]) {
  test(`${name} reports success only when archived came back FALSE`, async () => {
    const ok = await run(name, { id: 7 }, { id: 7, name: "Zz Probe", archived: false });
    assert.equal(ok.calls.length, 1);
    assert.match(ok.text, /active again/);

    // A 200 that leaves archived: true is the obvious case.
    const stuck = await run(name, { id: 7 }, { id: 7, archived: true });
    assert.match(stuck.text, /still reads archived: true/);
    assert.match(stuck.text, /Nothing was recovered/);

    // And the one that was wrong: an ABSENT field made `archived === true` false, so a null or
    // fieldless 200 was reported as "active again" with nothing verified.
    for (const data of [null, {}, { id: 7 }, { archived: null }]) {
      const { text } = await run(name, { id: 7 }, data);
      assert.match(text, /NOT\s+established/, JSON.stringify(data));
      assert.match(text, new RegExp(listTool));
      // Matched on the SUCCESS sentence specifically: the unknown branch legitimately contains the
      // words "active again" inside "whether it is active again is NOT established".
      assert.ok(!/is active again and/.test(text), JSON.stringify(data));
    }
  });
}

// The delete endpoints are "delete OR archive" and say which. Reporting "deleted or archived" left
// the caller to guess between a recoverable state and an unrecoverable one.
for (const [name, noun, listTool] of [
  ["reai_delete_customer", "Customer", "reai_list_customers"],
  ["reai_delete_supplier", "Supplier", "reai_list_suppliers"],
]) {
  test(`${name} reads the outcome instead of reporting both`, async () => {
    const deleted = await run(name, { id: 7 }, { outcome: "deleted" });
    assert.match(deleted.text, new RegExp(`${noun} 7 was DELETED outright`));
    assert.match(deleted.text, /nothing to unarchive/);

    const archived = await run(name, { id: 7 }, { outcome: "archived" });
    assert.match(archived.text, new RegExp(`${noun} 7 was ARCHIVED, not deleted`));
    assert.match(archived.text, /archived: true/, "it must say how to see the record again");
    assert.match(archived.text, new RegExp(listTool));
    assert.ok(!/DELETED outright/.test(archived.text));

    for (const data of [null, {}, { outcome: "something" }]) {
      const { text } = await run(name, { id: 7 }, data);
      assert.match(text, /no recognised outcome/, JSON.stringify(data));
    }
  });
}

test("the customer delete names the ordering trap, since archiving is what causes it", () => {
  const description = tool("reai_delete_customer").description;
  assert.match(description, /Referenced record is not accessible/);
  assert.match(description, /Delete the dependents first/);
  assert.match(description, /reai_unarchive_customer/);
});

test("the unarchive tool does not overclaim what it can rescue", () => {
  // Unarchiving the customer was the obvious hypothesis for the stranded orders, and it was tried
  // and failed. A tool that implied otherwise would send the next reader down the same path.
  const description = tool("reai_unarchive_customer").description;
  assert.match(description, /does not make that order deletable again/);
  assert.match(description, /products have no unarchive endpoint/);
});

test("the deletion-order and archive-visibility quirks reach the endpoints they concern", () => {
  const ids = (m, p) => quirksFor(m, p).map((q) => q.id);
  for (const path of ["/api/orders/{id}", "/api/customers/{id}", "/api/products/{id}", "/api/suppliers/{id}"]) {
    assert.ok(
      ids("DELETE", path).includes("delete-a-parent-and-its-children-become-undeletable"),
      `DELETE ${path}`,
    );
  }
  for (const path of ["/api/customers", "/api/suppliers"]) {
    assert.ok(ids("GET", path).includes("archived-records-need-an-explicit-filter-to-see"), path);
  }
  // A read cannot strand anything, so the ordering quirk must not appear on one.
  assert.ok(!ids("GET", "/api/orders").includes("delete-a-parent-and-its-children-become-undeletable"));
});

test("the ordering quirk states the recovery honestly, including what does not work", () => {
  const quirk = quirksFor("DELETE", "/api/orders/{id}").find(
    (q) => q.id === "delete-a-parent-and-its-children-become-undeletable",
  );
  assert.match(quirk.note, /NOT recoverable/);
  assert.match(quirk.note, /remove dependents BEFORE/);
  // Both halves: the endpoints that exist, and the case where they do not help.
  assert.match(quirk.note, /unarchive/);
  assert.match(quirk.note, /the 500\s+persisted/);
  // And the knock-on: an undeletable order takes its subscription with it.
  assert.match(quirk.note, /faktureringshistorikk/);
});

test("the archive-visibility quirk names the filter that works and the one that does not", () => {
  const quirk = quirksFor("GET", "/api/customers").find(
    (q) => q.id === "archived-records-need-an-explicit-filter-to-see",
  );
  assert.match(quirk.note, /`archived=true`/);
  assert.match(quirk.note, /includeArchived=true` is NOT it/);
  // The list tools already expose it, which is what makes the quirk actionable.
  for (const name of ["reai_list_customers", "reai_list_suppliers"]) {
    assert.ok(tool(name).inputSchema.archived, `${name} should take an archived filter`);
  }
});

/**
 * Every curated tool on an endpoint documented to answer `{outcome}` must read it.
 *
 * This repo has fixed the same bug five separate times, one endpoint at a time: customers, suppliers,
 * salary runs, expense vouchers, expenses. Each fix reported "deleted or archived" until someone
 * noticed, and each was found by hand. The spec has said which all along — `ApiLifecycleOutcomeRes`
 * is `{outcome: deleted|archived|reversed}` and **nineteen** operations declare it as their 200 — so
 * the sixth instance was always going to be found the same slow way.
 *
 * It was: an audit against the spec turned up reai_delete_product and reai_delete_company_bank, both
 * still answering "deleted or archived (HTTP 200)". The product one is the worst of the set, since a
 * deleted product is what strands orders permanently and products have no unarchive endpoint.
 *
 * Driven from the spec rather than from a list, so a new tool on any of the nineteen inherits the
 * requirement, and a twentieth endpoint gaining the envelope is covered the day it does.
 */
test("a curated tool on an {outcome} endpoint reports which outcome happened", async () => {
  const { readFileSync } = await import("node:fs");
  const { fileURLToPath } = await import("node:url");
  const spec = JSON.parse(
    readFileSync(fileURLToPath(new URL("../spec/reai-openapi.json", import.meta.url)), "utf8"),
  );

  // The operations whose success response is the lifecycle envelope. Read from every content type:
  // this spec declares 368 of its responses under the wildcard, and only 12 under application/json.
  const outcomeOps = new Set();
  for (const [path, item] of Object.entries(spec.paths ?? {})) {
    for (const [method, op] of Object.entries(item)) {
      const ok = op?.responses?.["200"] ?? op?.responses?.["201"];
      const schema = Object.values(ok?.content ?? {}).find((c) => c?.schema)?.schema;
      if (schema?.$ref?.endsWith("ApiLifecycleOutcomeRes")) outcomeOps.add(`${method.toUpperCase()} ${path}`);
    }
  }
  assert.ok(outcomeOps.size >= 15, `expected the lifecycle envelope on many endpoints, saw ${outcomeOps.size}`);

  // What the handler DOES, not what its description says: a tool can describe the two outcomes
  // beautifully and still report "one of these happened". The observable is the note it produces for
  // each outcome value, so drive it three times and require deleted and archived to differ.
  //
  // Arguments are built from each tool's OWN schema. The first version hardcoded `id: 7`, and three
  // tools that take departmentId, assetId and warehouseId threw on every call — identical error text,
  // which the comparison then read as identical notes and reported as three tools ignoring the
  // outcome. They were doing it correctly. A test that accuses the innocent is worse than no test, so
  // "could not exercise" is now its own outcome, asserted separately and loudly.
  const sentinelFor = (name, schema) => {
    const def = schema?._def?.innerType?._def ?? schema?._def ?? {};
    if (Array.isArray(def.values) && def.values.length > 0) return def.values[0];
    if (def.typeName === "ZodBoolean") return true;
    if (def.typeName === "ZodNumber") return 7;
    if (/date/i.test(name)) return "2026-03-04";
    return `Zz ${name}`;
  };

  const offenders = [];
  const unexercised = [];
  let checked = 0;
  for (const t of registeredTools) {
    const hits = (t.apiPaths ?? []).filter(([method, path]) => outcomeOps.has(`${method} ${path}`));
    if (hits.length === 0) continue;
    checked += 1;

    const args = { tenantId: 2783 };
    for (const [field, schema] of Object.entries(t.inputSchema ?? {})) {
      if (field === "tenantId") continue;
      args[field] = sentinelFor(field, schema);
    }

    const notes = new Map();
    const failures = [];
    for (const outcome of ["deleted", "archived", "reversed"]) {
      try {
        const validated = z.object(t.inputSchema).parse(args);
        const result = await t.handler(validated, {
          client: {
            request: async (req) => ({
              // Only the DELETE answers the envelope; a preflight read gets a plausible record.
              data:
                req.method === "DELETE"
                  ? { outcome }
                  : { id: 7, name: "Zz", status: "under_process", archived: false },
              status: 200,
            }),
            deepLink: () => "link",
          },
          config: { writeMode: "full", tenantId: 2783, allowExternalSend: false },
          session: {},
        });
        // The NOTE, not the whole text. ok() echoes the response body underneath, and that body
        // contains the outcome field itself — so comparing full text let the pre-fix version pass:
        // `{"outcome":"deleted"}` and `{"outcome":"archived"}` differ without the tool having said
        // anything about either. The prose above the body is where a tool states what happened, and
        // for a tool that never wrote one it is empty for all three, which is exactly the finding.
        const text = result.content.find((c) => c.type === "text")?.text ?? "";
        const bodyStart = text.search(/^[[{]/m);
        notes.set(outcome, (bodyStart >= 0 ? text.slice(0, bodyStart) : text).trim());
      } catch (err) {
        failures.push(`${outcome}: ${err?.message ?? err}`);
      }
    }

    if (notes.size < 3) {
      unexercised.push(`${t.name} — ${failures.join(" | ").slice(0, 200)}`);
      continue;
    }
    // All THREE pairwise, not just deleted vs archived. Review's point, and it is the right one: the
    // harness was already driving `reversed` and then ignoring what came back, so a tool that folded
    // a reversal into its archived or unknown branch passed — on vouchers, expenses and salary runs,
    // where a reversal POSTS to the ledger and is the most consequential of the three to get wrong.
    const pairs = [
      ["deleted", "archived"],
      ["deleted", "reversed"],
      ["archived", "reversed"],
    ];
    const same = pairs.filter(([a, b]) => notes.get(a) === notes.get(b));
    if (same.length > 0) {
      offenders.push(
        `${t.name} (${hits.map(([m, p]) => `${m} ${p}`).join(", ")}) — same note for ` +
          same.map(([a, b]) => `${a}/${b}`).join(" and "),
      );
    }
  }

  assert.deepEqual(
    unexercised,
    [],
    "these could not be driven at all, so this test proves nothing about them — fix the harness",
  );
  assert.ok(checked >= 8, `expected several curated tools on these endpoints, found ${checked}`);
  assert.deepEqual(
    offenders,
    [],
    "these call an endpoint that says whether it deleted or archived, and report the same thing either way",
  );
});

test("the two tools this audit caught now name the consequence, not just the outcome", () => {
  // Naming the outcome is half of it. What a caller needs is what the outcome MEANS here, and for
  // products it is unusually sharp: archived is recoverable-looking and not recoverable, because
  // products have no unarchive endpoint.
  const product = tool("reai_delete_product").description;
  assert.ok(product, "reai_delete_product should exist");
  for (const pattern of [/deleted or archived/i]) {
    assert.ok(!pattern.test(product), "the description should no longer hedge between the two");
  }
});
